version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true #docker run -it
    stdin_open: true #docker run -it
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgres/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTRES_HOST_AUTH_METHOD=trust'